<a href="https://colab.research.google.com/github/denisoon/simple-datascience/blob/main/Numpy%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import numpy as np

In [4]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [5]:
x.shape


(4,)

In [6]:
x.size

4

In [7]:
x.dtype

dtype('int64')

In [9]:
x[[True, False, True, False]]

array([0, 2])

In [10]:
x >= 2

array([False, False,  True,  True])

In [12]:
x [x >= 2]

array([2, 3])